name: Run PHP Hello World

on:
  push:
    branches:
      - main

jobs:
  php-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run PHP script
        run: php index.php
